version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        MAP_ID: ${MAP_ID-1000}
    volumes:
      - .:/var/www
    ports:
      - ${NODE_PORT-8080}:${NODE_PORT-8080}
    command: [ "sh", "-c", "npm install && npm run dev -- --host" ]
    expose: 
      - ${NODE_PORT-8080}

