version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
      args:
        MAP_ID: ${MAP_ID-1000}
    volumes:
      - .:/var/www
    ports:
      - ${NODE_PORT-8080}:${NODE_PORT-8080}
    expose: 
      - ${NODE_PORT-8080}

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    depends_on:
      - app
    links: 
      - app
    volumes:
      - .:/var/www
    ports:
      - 80:80

